
name: jibjab
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  vector_graphics: ^1.1.19
  internet_connection_checker_plus: ^2.7.2
  go_router: ^16.1.0
  gap: ^3.0.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  logger: ^2.6.2
  google_fonts: ^6.3.0
  get_it: ^8.2.0
  fpdart: ^1.1.1
  http: ^1.5.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  flutter_spinkit: ^5.2.2
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.13.0
  video_player: ^2.10.1
  chewie: ^1.13.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.10
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter_gen:
  output: lib/core/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/poppins/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
